We are currently seeking GitHub users interested in sponsoring the further development of this code
so that it may progress into the nbext stage involving actual hardware prototyping experiments.
github: ["example_inspred_user1, example_inspired_user2"] - please contact me for more info or to express interest 
